### ISSUE TITLE
Request to tag a version

### ISSUE THREAD

**Issue by dianarg** [dropbox/json11#115]
I am interested in using this library, but I would prefer if it had a version. Could you please add one?

**Comment by artwyman** [comment]
We don't do official versioned releases.  The library is rarely updated, and we don't generally make compatibility-breaking changes, though.
For stability, I recommend you pull this repo with a specific commit hash, so you can decide for yourself when to move to a newer version.

**Comment by dianarg** [comment]
We'd like to refer to a tag in our documentation, so we plan to fork and tag our fork. As long as you never plan to add a tag to your repo, there should be no conflict. I hope this understanding is correct.

**Comment by artwyman** [comment]
We have no plans to add tags, but I wouldn't promise never to do so.  So long as your tag name is unique, though, I wouldn't expect any problems.
