### ISSUE TITLE
[Feature] conan package manager support

### ISSUE THREAD

**Issue by alexandrudsc** [dropbox/json11#135]
Hello,

I was curious about your opinion regarding the conan package manager. For me it looks a lot easier to share a library as a package. I've also submitted a pr https://github.com/dropbox/json11/pull/134, if you're interested could you please take a look?

**Comment by artwyman** [comment]
Interesting idea, but seems like it would be a major change and would make this repo opinionated on tools rather than being simple and generic.  No new feature development is intended for this repo, so I'm going to close this out.
