### ISSUE TITLE
Order serealization Json::object

### ISSUE THREAD

**Issue by vincenzopalazzo** [dropbox/json11#136]
Hello guys,

I have a problem with serialization json into a test

I had to keep an isConverted parameter because I have an object of the same type inside the object to be serialized.
Leaving aside this I have performed all the correct steps but why do I get a wrong order?

I have this code
`Json Person::toJSon() {

    if(isConverted || boyOrGirlFrined == nullptr){
        return Json::object{
                {"name", name},
                {"surname", surname},
                {"sex", sex},
        };
    }
    boyOrGirlFrined->isConverted = true;
    return Json::object{
            {"name", name},
            {"surname", surname},
            {"sex", sex},
            {"AnimaGemella", boyOrGirlFriend->toJSon()},
    };
}`

with i get this result
`{"AnimaGemella": {"name": "Sara", "sex": "f", "surname": "Durante"}, "name": "Vincenzo", "sex": "m", "surname": "Palazzo"}`

and not it?
`{"name": "Vincenzo", "sex": "m", "surname": "Palazzo", "AnimaGemella": {"name": "Sara", "sex": "f", "surname": "Durante"}}`

Sorry for my English but I'm learning

**Comment by j4cbo** [comment]
json11 maps the json object type to `std::map`, which doesn't preserve the original order. Most other languages' implementations behave the same way.

**Comment by vincenzopalazzo** [comment]
@j4cbo Thanks for your answer
