### ISSUE TITLE
No API to add Json (f.e. array) to Json::object outside of ctor.

### ISSUE THREAD

**Issue by alecazam** [dropbox/json11#147]
All apis seem to return a const Json& that cannot be modified.  This is rather inconvenient when building a json tree to have to have all of the data up-front in a constructor, especially if conditionals are involved with what fields are saved/loaded.   Am I missing an API here?

**Comment by artwyman** [comment]
`Json` objects are immutable by design.  If you want to build up your data incrementally you can use a `son::object` (which is a type alias for a map) as a builder, then turn it into a `Json` object when you're done.
