### ISSUE TITLE
Is this library thread safe?

### ISSUE THREAD

**Issue by marshal09** [dropbox/json11#29]
Hi all

Very good library!!
I have question

I want to use the library in different threads (not gonna use the same object on different threads).
Is the library thread safe?

thanks in advance =]

**Comment by artwyman** [comment]
Yes, json11 is safe for the purposes you have in mind.  There is no hidden global data, so it's safe to use/parse distinct Json objects on different threads.  Also, Json objects are not mutable by any method other than assignment, so it's safe to use the same object across multiple threads so long as you're not assigning to it.
