### ISSUE TITLE
Behavior of std::cin.get for g++4.8 and std c++ library breaks  "test --stdin"

### ISSUE THREAD

**Issue by justinlw** [dropbox/json11#3]
The behavior of **std::cin.get()** breaks **parse_from_stdin()** in *test.cpp* when /g++ 4.8 and the Linux std c++ library.     

When using *test --stdin*,  **std::cin.get()** returns *-1* when it encounters *EOF* before it actually sets the *EOF* status on **std::cin**, indirectly causing **Json::parse()** to fail, complaining about  *"unexpected trailing (-1)".*

**Comment by artwyman** [comment]
We're using g++4.9 as default requirement now.  Willing to revisit this if it happens there too, but closing for now.
