### ISSUE TITLE
Json::m_ptr looks like std::unique_ptr would be more suited

### ISSUE THREAD

**Issue by Amleto** [dropbox/json11#45]
`Json::m_ptr` looks like `std::unique_ptr` would be more suited? I didn't see any sharing that suggests `shared_ptr` is needed, but only eye-balled it.

**Comment by j4cbo** [comment]
The implicit copy constructor of `Json` will copy the `shared_ptr`, thus making a shallow copy of the object (increasing the refcount). This is safe since the underlying objects are immutable; the intention was to make `Json` a lightweight handle-like type.
