### ISSUE TITLE
String Vector to Json::array

### ISSUE THREAD

**Issue by hassanfarid** [dropbox/json11#63]
I have std::vector<std::string>
each string value is json object = "{"key":"value"}"

How can make a Json::object of value
"[{"key":"value"}, {"key":"value"}]"

**Comment by j4cbo** [comment]
Iterate through the vector and use `Json::parse` on each string, build up a `vector<Json>`, then convert the result to `Json`

**Comment by hassanfarid** [comment]
I found a solution myself:

Use Json::array constructor,
`Json j = Json::array({vector_of_string_with_json_formatted_string});`
`cout<<j.dump();`

this would result in string:
"[[{"key":"value"}, {"key":"value"}]]"

so then you can use below code to get required object format,

`cout<<j[0].dump();`

**Comment by hassanfarid** [comment]
I forgot the solution that I found earlier, and found it useful finding it here. Thanks myself. :)
