### ISSUE TITLE
Support for construction from std::unordered_map

### ISSUE THREAD

**Issue by dremon** [dropbox/json11#74]
Would be nice to have a Json constructor accept the std::unordered_map parameter as an object as well.

**Comment by artwyman** [comment]
It does, via the constructor here: https://github.com/dropbox/json11/blob/master/json11.hpp#L108

You can see some code which exercises it here: https://github.com/dropbox/json11/blob/master/test.cpp#L164

Are you seeing it not work in a specific scenario?

**Comment by dremon** [comment]
You are right, it works. Was doing it in a wrong way (via Json::object which just appears to be a typedef). Issue can be closed.
