### ISSUE TITLE
any luck getting this to compile on older gccs? say 4.6/7

### ISSUE THREAD

**Issue by victusfate** [dropbox/json11#8]
I began modifying a fork to remove finals etc, but that may contrast greatly with the design/intent (or required utilities like regex). Dig this library cause of its footprint. Sometime soon we'll be migrating towards gcc 4.8 in production

**Comment by lauraeci** [comment]
Is this fork publicly available?  Looking for a good json library for 4.6.  Thanks!  :)

**Comment by j4cbo** [comment]
We're not planning on supporting anything older than 4.8 (we've actually moved to 4.9 internally).
