### ISSUE TITLE
Crash with Json(o).dump() in Xcode 7+8

### ISSUE THREAD

**Issue by weepy** [dropbox/json11#81]
I found Json(o).dump() extremely useful for debugging. 

Unfortunately I'm finding that it now crashes XCode 7 and 8. Anyone getting similar problems ? 

J

**Comment by artwyman** [comment]
What's "o" in the case you're looking at?  Can you create some example code?
We definitely use dump() in our code, and build with Xcode 7 and 8, so I don't think the crash is quite as broad as you're describing, but it might be specific to particular JSON structures.

**Comment by weepy** [comment]
Sorry I wasn't explicit. It occurs during debugging when using the console. As in :
```
expr Json(o).dump()
```

o is jump some arbitrary Json11 object.

**Comment by artwyman** [comment]
Oh, if it's a debugger-specific problem, then I don't have any experience with it in order to help.  I've found that kind of debugger feature to be unreliable at best when I've used it.
